# Generated by Django 4.2.6 on 2023-10-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тип мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('max_count', models.PositiveIntegerField(default=10, verbose_name='Максимальное количество участников')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('addres', models.CharField(max_length=100, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.type_event')),
            ],
        ),
    ]
